### ISSUE TITLE
hx-target code completion

### ISSUE THREAD

**Issue by wimdeblauwe** [hugohomesquita/htmx-jetbrains#2]
It would be great to have code completion inside of `hx-target` so it shows a list of known id values in the html or CSS selectors (See https://htmx.org/attributes/hx-target/). Even better would be if we could "jump" from the hx-target value to the place where the id is declared (Similar to how you can "jump" from `<label for="my-field" ...` to where this `my-field` is declared by using CTRL-click)

**Comment by hugohomesquita** [comment]
Great suggestion, I'll add

**Comment by hugohomesquita** [comment]
Done!
