### ISSUE TITLE
hx-target code completion inserts double #

### ISSUE THREAD

**Issue by wimdeblauwe** [hugohomesquita/htmx-jetbrains#3]
I just tried the code completion for `hx-target`, but it seems a double `#` is inserted when selecting a suggestion using TAB or ENTER.
![double hash sign bug](https://user-images.githubusercontent.com/1115823/208841787-b861ea21-01b0-4361-8d0f-4593169abd6a.gif)

**Comment by eydunn** [comment]
#8
