### ISSUE TITLE
Support IntelliJ 2023.1

### ISSUE THREAD

**Issue by wimdeblauwe** [hugohomesquita/htmx-jetbrains#6]
IntelliJ 2023.1 shows the plugin as not compatible. Can it be made compatible?

**Comment by hugohomesquita** [comment]
I will update

**Comment by eamigo86** [comment]
+1

**Comment by sorenbronsted** [comment]
+1

**Comment by eydunn** [comment]
+1

**Comment by eydunn** [comment]
https://github.com/hugohomesquita/htmx-jetbrains/pull/7

**Comment by hugohomesquita** [comment]
Send! waiting for jetbrains review.

Thanks @eydunn
